### ISSUE TITLE
Create `Request` Model

### ISSUE THREAD

**Issue by Lapotor** [RadioRoster/backend#23]
**Description:**
This task involves creating a `Request` model for the Laravel project. The `Request` model will represent the data structure and attributes associated with user requests in the application. This model will be used to interact with the database and perform operations related to requests, such as retrieval, creation, and deletion.

<details>
<summary>Model Decleration</summary>

```YAML
  Request:
    type: object
    required:
      - id
      - name
      - message
      - created_at
    properties:
      id:
        type: integer
      name:
        type: string
      message:
        type: string
      created_at:
        type: string
        format: date-time
```
</details>

**Tasks:**

- [ ] Generate a new `Request` model using the Laravel Artisan CLI.
- [ ] Define the attributes and relationships for the `Request` model, including fields like `id`, `name`, `message`, and `created_at`.
- [ ] Implement any necessary validation rules for the model attributes.
- [ ] Set up the database migration to create the corresponding table for the `Request` model.
- [ ] Test the model to ensure it can perform basic operations like saving, retrieving, and deleting requests.

**Acceptance Criteria:**
- The `Request` model should be created and properly defined with all required attributes.
- The model should be associated with the database and able to perform CRUD operations.
- The model's validation rules should be applied and tested for accuracy.
