### ISSUE TITLE
Create `User` Model

### ISSUE THREAD

**Issue by Lapotor** [RadioRoster/backend#24]
## Description:

This work item involves the creation of a `User` model in the Laravel project. The `User` model will serve as the representation of a registered user within the application. It will include attributes such as `id`, `name`, `email`, `password`, `created_at`, `updated_at`, and `role_id`.

The `User` model will be responsible for interacting with the user data stored in the database. This includes tasks such as user registration, authentication, and managing user-related information.

<details>
<summary>Model Decleration</summary>

```YAML
  User:
    type: object
    required:
      - id
      - created_at
      - updated_at
      - name
      - email
      - password
    properties:
      id:
        type: integer
      created_at:
        type: string
        format: date-time
      updated_at:
        type: string
        format: date-time
      name:
        type: string
      email:
        type: string
      email_verified_at:
        type: string
        format: date-time
      password:
        type: string
        format: password
      role:
        type: integer
```
</details>

## Tasks:

- [ ] Generate the `User` model using Laravel's artisan command-line tool.
- [ ] Define the attributes (`id`, `name`, `email`, `password`, `created_at`, `updated_at`, and `role_id`) and their respective data types in the `User` model.
- [ ] Implement any necessary relationships with other models (e.g., roles, permissions).
- [ ] Set up the database migration for creating the `users` table.
- [ ] Add validation rules for user input in the `User` model.
- [ ] Implement methods for user authentication and registration.
- [ ] Add any necessary custom functionality related to user management.

## Acceptance Criteria:

- The `User` model is successfully generated.
- The model includes the specified attributes and relationships.
- The database migration for the `users` table is created and executed.
- Validation rules are implemented to ensure data integrity.
- User authentication and registration functionality is operational.
- Unit tests for the `User` model pass successfully.
