### ISSUE TITLE
Create `Role` Model

### ISSUE THREAD

**Issue by Lapotor** [RadioRoster/backend#25]
## Description:
This task involves creating the `Role` model in the Laravel project. The `Role` model will serve as a representation of user roles within the application. Roles define the permissions and access levels that users have. This model will be responsible for storing role-related information in the database and providing methods for interacting with roles.

<details>
<summary>Model Decleration</summary>

```YAML
  Role:
    type: object
    required:
      - id
      - created_at
      - updated_at
      - name
      - permissions
    properties:
      id:
        type: integer
      created_at:
        type: string
        format: date-time
      updated_at:
        type: string
        format: date-time
      name:
        type: string
      permissions:
        type: object
```
</details>

## Tasks:

- [ ] Generate the `Role` model file.
- [x] Define the attributes and relationships for the `Role` model.
- [x] Set up the database migration for the `roles` table.
- [ ] Implement any necessary validation rules for role attributes.
- [ ] Create methods for querying and managing roles.
- [ ] Write unit tests to ensure the functionality of the `Role` model.

## Acceptance Criteria:
- The `Role` model file is created and located in the appropriate directory.
- The model defines attributes such as `id`, `name`, `created_at`, `updated_at`, and any other relevant fields.
- The model has relationships defined as needed (e.g., with users).
- The database migration for the `roles` table is created and can be run to create the corresponding database table.
- Validation rules are in place to ensure data integrity for role attributes.
- Methods for querying and managing roles (e.g., creating, updating, deleting) are implemented and functional.
- Unit tests are written to cover the methods and functionality of the `Role` model.

## Additional Information:
- Refer to the project's coding standards and conventions for naming conventions and style guidelines while creating the `Role` model.
